parameters:
#    btanase_multi_select_autocomplete.example.class: Btanase\MultiSelectAutocompleteBundle\Example

services:
#    btanase_multi_select_autocomplete.example:
#        class: %btanase_multi_select_autocomplete.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
